[[pages]]
name = "Visualizing Demographic"
icon = "ğŸ "
path = "app.py"

[[pages]]
name = "Introduction"
icon = ":books:"
path = "pages/introduction.py"

[[pages]]
name = "Dataset Analysis"
icon = ":file_cabinet:"
path = "pages/dataset.py"

[[pages]]
path = "pages/vis.py"
name = "Visualisations"
icon = ":world_map:"

[[pages]]
path = "pages/lod.py"
name = "LOD"
icon = ":linked_paperclips:"
